heartbeat.config.monitors:
  path: ${path.config}/monitors.d/*.yml
  reload.enabled: false
  reload.period: 5s

heartbeat.monitors:
  - type: http
    id: api-gateway
    name: API Gateway Service
    schedule: '@every 5s'
    hosts: ["http://gateway_container:4000/gateway-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: user
    name: Users Service
    schedule: '@every 5s'
    hosts: ["http://users_container:4001/user-health"]
    check.request.method: GET
    check.response.status: [200]

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

monitoring.enabled: true

output.elasticsearch:
  hosts: ['http://elasticsearch_container:9200']
  username: 'elastic'
  password: 'admin1234'